language: python
python:
    - "2.7"
    - "3.5"

install:
    - pip install -r requirements.txt
    - wget -O cdb.tar.gz https://connectordb.io/download/connectordb_server_current_linux_amd64.tar.gz
    - tar xvzf cdb.tar.gz
    - export PATH=$TRAVIS_BUILD_DIR/bin:$PATH
    - pip install coveralls

before_script:
    - connectordb create testdb --test
    - connectordb -l=ERROR start testdb &

script: nosetests --with-coverage --cover-package=connectordb

after_success: coveralls
