language: python
python:
    - "2.7"
    - "3.5"

install:
    - pip install -r requirements.txt
    - wget -O cdb.tar.gz https://github.com/connectordb/connectordb/releases/download/v0.3.0a1/connectordb0.3.0a1.tar.gz
    - tar xvzf cdb.tar.gz
    - export PATH=$TRAVIS_BUILD_DIR/bin:$PATH
    - pip install coveralls

before_script:
    - connectordb create testdb --test
    - connectordb start testdb
    - connectordb -l=ERROR run testdb &

script: nosetests --with-coverage --cover-package=connectordb

after_success: coveralls
